FROM nginx

WORKDIR /usr/share/nginx/html

RUN rm *
COPY . .

#BUILD
#"build-docker": "docker build -t webchat_front .",
#"run-docker": "docker run --rm --name webchat_front -d -p 80:80 webchat_front"